import { ISupplier, ISupplierEvaluation, IContract } from './types'

const baseDate = new Date('2026-05-15')

export const mockSuppliers: ISupplier[] = [
  {
    id: 'sup-001',
    code: 'SUP-001',
    name: 'Vải ABC Trading Co.',
    taxId: '0312456789',
    type: 'Manufacturer',
    address: '123 Đường Vải Sợi, P. Phú Thọ Hòa, Q. Tân Phú, TP.HCM',
    phone: '0901 234 567',
    email: 'info@vaiabctrading.vn',
    leadTime: 5,
    paymentTerms: 'NET 30',
    currency: 'VND',
    status: 'Active',
    rating: 4.8,
    contacts: [
      {
        id: 'con-001',
        name: 'Nguyễn Văn An',
        title: 'Giám đốc kinh doanh',
        phone: '0901 234 567',
        email: 'an@vaiabctrading.vn',
        role: 'Primary',
        isPrimary: true,
      },
      {
        id: 'con-002',
        name: 'Trần Thị Lan',
        title: 'Kế toán công nợ',
        phone: '0901 234 568',
        email: 'lan@vaiabctrading.vn',
        role: 'Accounting',
        isPrimary: false,
      },
      {
        id: 'con-003',
        name: 'Lê Văn Kho',
        title: 'Thủ kho / Giao hàng',
        phone: '0901 234 569',
        email: '',
        role: 'Logistics',
        isPrimary: false,
      },
    ],
    products: [
      {
        id: 'prod-001',
        name: 'Vải Cotton Trắng',
        unit: 'mét',
        unitPrice: 120000,
        moq: 50,
        leadTime: 5,
        notes: 'Khổ 150cm',
      },
      {
        id: 'prod-002',
        name: 'Vải Cotton Xanh Navy',
        unit: 'mét',
        unitPrice: 135000,
        moq: 50,
        leadTime: 5,
        notes: 'Nhuộm theo order',
      },
      {
        id: 'prod-003',
        name: 'Vải Cotton Đỏ Đô',
        unit: 'mét',
        unitPrice: 140000,
        moq: 30,
        leadTime: 7,
        notes: 'Màu theo mẫu',
      },
      {
        id: 'prod-004',
        name: 'Vải Linen Tự Nhiên',
        unit: 'mét',
        unitPrice: 185000,
        moq: 20,
        leadTime: 10,
        notes: 'Nhập từ Ấn Độ',
      },
    ],
    createdAt: new Date(baseDate.getTime() - 365 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(baseDate.getTime() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'sup-002',
    code: 'SUP-002',
    name: 'Phụ Liệu XYZ',
    taxId: '0387654321',
    type: 'Trader',
    address: '456 Đường Phụ Liệu, P. Hiệp Phú, Q. 9, TP.HCM',
    phone: '0912 345 678',
    email: 'info@phulieuxyz.vn',
    leadTime: 3,
    paymentTerms: 'COD',
    currency: 'VND',
    status: 'Active',
    rating: 4.5,
    contacts: [
      {
        id: 'con-004',
        name: 'Trần Thị Bình',
        title: 'Quản lý bán hàng',
        phone: '0912 345 678',
        email: 'binh@phulieuxyz.vn',
        role: 'Primary',
        isPrimary: true,
      },
    ],
    products: [
      {
        id: 'prod-005',
        name: 'Nút nhựa 15mm',
        unit: 'cái',
        unitPrice: 500,
        moq: 1000,
        leadTime: 3,
        notes: 'Nhiều màu',
      },
      {
        id: 'prod-006',
        name: 'Khóa kéo kim loại',
        unit: 'cái',
        unitPrice: 1200,
        moq: 500,
        leadTime: 3,
        notes: 'Silver',
      },
    ],
    createdAt: new Date(baseDate.getTime() - 300 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(baseDate.getTime() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'sup-003',
    code: 'SUP-003',
    name: 'Vải Lụa Hạnh Phúc',
    taxId: '0367654890',
    type: 'Manufacturer',
    address: '789 Đường Lụa, P. 1, Q. Gò Vấp, TP.HCM',
    phone: '0923 456 789',
    email: 'contact@vailuahp.vn',
    leadTime: 10,
    paymentTerms: 'NET 60',
    currency: 'VND',
    status: 'Active',
    rating: 4.1,
    contacts: [
      {
        id: 'con-005',
        name: 'Lê Minh Châu',
        title: 'Giám đốc',
        phone: '0923 456 789',
        email: 'chau@vailuahp.vn',
        role: 'Primary',
        isPrimary: true,
      },
    ],
    products: [
      {
        id: 'prod-007',
        name: 'Vải Lụa Trắng',
        unit: 'mét',
        unitPrice: 250000,
        moq: 20,
        leadTime: 10,
        notes: 'Khổ 140cm',
      },
    ],
    createdAt: new Date(baseDate.getTime() - 250 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(baseDate.getTime() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'sup-004',
    code: 'SUP-004',
    name: 'NCC Nút Bấm 123',
    taxId: '0378901234',
    type: 'Trader',
    address: '321 Đường Nút, P. 5, Q. Bình Tân, TP.HCM',
    phone: '0934 567 890',
    email: 'contact@nutbam123.vn',
    leadTime: 2,
    paymentTerms: 'Prepaid',
    currency: 'VND',
    status: 'Active',
    rating: 3.8,
    contacts: [
      {
        id: 'con-006',
        name: 'Phạm Quốc Hùng',
        title: 'Chủ tịch',
        phone: '0934 567 890',
        email: 'hung@nutbam123.vn',
        role: 'Primary',
        isPrimary: true,
      },
    ],
    products: [
      {
        id: 'prod-008',
        name: 'Nút bấm tròn 20mm',
        unit: 'cái',
        unitPrice: 800,
        moq: 500,
        leadTime: 2,
        notes: 'Plastic',
      },
    ],
    createdAt: new Date(baseDate.getTime() - 180 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(baseDate.getTime() - 10 * 60 * 1000),
  },
  {
    id: 'sup-005',
    code: 'SUP-005',
    name: 'Khóa Kéo Việt Nam',
    taxId: '0389012345',
    type: 'Individual',
    address: '654 Đường Khóa, P. Tân Bình, Q. Tân Bình, TP.HCM',
    phone: '0945 678 901',
    email: 'order@khoakeoVN.vn',
    leadTime: 7,
    paymentTerms: 'NET 15',
    currency: 'VND',
    status: 'Suspended',
    rating: 3.2,
    contacts: [
      {
        id: 'con-007',
        name: 'Ngô Thị Dung',
        title: 'Owner',
        phone: '0945 678 901',
        email: 'dung@khoakeoVN.vn',
        role: 'Primary',
        isPrimary: true,
      },
    ],
    products: [
      {
        id: 'prod-009',
        name: 'Khóa kéo nylon #5',
        unit: 'cái',
        unitPrice: 1500,
        moq: 200,
        leadTime: 7,
        notes: 'Standard',
      },
    ],
    createdAt: new Date(baseDate.getTime() - 120 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(baseDate.getTime() - 30 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'sup-006',
    code: 'SUP-007',
    name: 'NCC Hàng Giả Bị Ban',
    taxId: '0390123456',
    type: 'Trader',
    address: 'Unknown',
    phone: 'N/A',
    email: 'N/A',
    leadTime: 0,
    paymentTerms: 'COD',
    currency: 'VND',
    status: 'Blacklisted',
    blacklistReason: 'Cung cấp hàng giả, bị xử lý tháng 02/2026',
    rating: 1,
    contacts: [],
    products: [],
    createdAt: new Date(baseDate.getTime() - 200 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(baseDate.getTime() - 60 * 24 * 60 * 60 * 1000),
  },
]

export const mockEvaluations: ISupplierEvaluation[] = [
  {
    id: 'eval-001',
    supplierId: 'sup-001',
    period: 'Q3-2025',
    qualityScore: 5,
    deliveryScore: 4,
    priceScore: 4,
    serviceScore: 5,
    totalScore: 4.5,
    note: 'Chất lượng tốt, giao hàng trong hạn',
    evaluatedBy: 'Lê Minh Tuấn',
    createdAt: new Date('2025-10-15'),
  },
  {
    id: 'eval-002',
    supplierId: 'sup-001',
    period: 'Q4-2025',
    qualityScore: 5,
    deliveryScore: 5,
    priceScore: 4,
    serviceScore: 5,
    totalScore: 4.8,
    note: 'Xuất sắc, đạt yêu cầu cao nhất',
    evaluatedBy: 'Lê Minh Tuấn',
    createdAt: new Date('2026-01-15'),
  },
  {
    id: 'eval-003',
    supplierId: 'sup-001',
    period: 'Q1-2026',
    qualityScore: 4,
    deliveryScore: 5,
    priceScore: 3,
    serviceScore: 4,
    totalScore: 4.1,
    note: 'Giá hơi cao, cần thương lượng lại',
    evaluatedBy: 'Lê Minh Tuấn',
    createdAt: new Date('2026-04-15'),
  },
  {
    id: 'eval-004',
    supplierId: 'sup-002',
    period: 'Q4-2025',
    qualityScore: 4,
    deliveryScore: 4,
    priceScore: 5,
    serviceScore: 4,
    totalScore: 4.2,
    note: 'Giá cạnh tranh, giao hàng nhanh',
    evaluatedBy: 'Nguyễn Hữu Khánh',
    createdAt: new Date('2026-01-15'),
  },
  {
    id: 'eval-005',
    supplierId: 'sup-002',
    period: 'Q1-2026',
    qualityScore: 4,
    deliveryScore: 3,
    priceScore: 5,
    serviceScore: 3,
    totalScore: 3.8,
    note: 'Giao hàng bị chậm, cần cải thiện',
    evaluatedBy: 'Nguyễn Hữu Khánh',
    createdAt: new Date('2026-04-15'),
  },
  {
    id: 'eval-006',
    supplierId: 'sup-003',
    period: 'Q3-2025',
    qualityScore: 3,
    deliveryScore: 4,
    priceScore: 3,
    serviceScore: 4,
    totalScore: 3.4,
    note: 'Chất lượng trung bình, cần theo dõi',
    evaluatedBy: 'Vũ Quốc Hùng',
    createdAt: new Date('2025-10-15'),
  },
  {
    id: 'eval-007',
    supplierId: 'sup-003',
    period: 'Q1-2026',
    qualityScore: 4,
    deliveryScore: 3,
    priceScore: 3,
    serviceScore: 3,
    totalScore: 3.4,
    note: 'Chất lượng có cải thiện, giao hàng tương ứng',
    evaluatedBy: 'Vũ Quốc Hùng',
    createdAt: new Date('2026-04-15'),
  },
]

export const mockContracts: IContract[] = [
  {
    id: 'ct-001',
    supplierId: 'sup-001',
    contractNo: 'CT-2026-001',
    startDate: new Date('2026-01-01'),
    endDate: new Date('2027-12-31'),
    paymentTerms: 'NET 30',
    discountRate: 5,
    minOrderValue: 50000000,
    status: 'Active',
    fileUrl: '/contracts/CT-2026-001.pdf',
    createdAt: new Date('2025-12-20'),
  },
  {
    id: 'ct-002',
    supplierId: 'sup-002',
    contractNo: 'CT-2026-002',
    startDate: new Date('2025-09-01'),
    endDate: new Date('2027-08-31'),
    paymentTerms: 'NET 60',
    discountRate: 3,
    minOrderValue: 20000000,
    status: 'Active',
    fileUrl: '/contracts/CT-2026-002.pdf',
    createdAt: new Date('2025-08-15'),
  },
  {
    id: 'ct-003',
    supplierId: 'sup-003',
    contractNo: 'CT-2025-003',
    startDate: new Date('2024-01-01'),
    endDate: new Date('2025-12-31'),
    paymentTerms: 'NET 30',
    discountRate: 0,
    minOrderValue: 30000000,
    status: 'Expired',
    fileUrl: '/contracts/CT-2025-003.pdf',
    createdAt: new Date('2023-12-20'),
  },
]
