import { IGRN, IReturn } from './types'

const baseDate = new Date('2026-05-15')

export const mockGoodsReceipts: IGRN[] = [
  {
    id: 'grn-001',
    code: 'GRN-2026-001',
    poId: 'po-001',
    prId: 'pr-007',
    supplierId: 'sup-001',
    supplierName: 'Vải ABC Trading Co.',
    status: 'Completed',
    isPartial: false,
    items: [
      {
        id: 'grni-001',
        productId: 'prod-001',
        productName: 'Vải Cotton Trắng',
        expectedQty: 200,
        receivedQty: 200,
        acceptedQty: 200,
        rejectedQty: 0,
        unit: 'mét',
        qcStatus: 'Pass',
        batchNo: 'LOT-05132',
        storageLocation: 'A2-04',
        notes: 'Đạt chuẩn, khổ đúng 150cm',
      },
    ],
    receivedDate: new Date(baseDate.getTime() - 5 * 24 * 60 * 60 * 1000),
    createdAt: new Date(baseDate.getTime() - 5 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(baseDate.getTime() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'grn-002',
    code: 'GRN-2026-002',
    poId: 'po-002',
    prId: 'pr-008',
    supplierId: 'sup-002',
    supplierName: 'Phụ Liệu XYZ',
    status: 'QC In Progress',
    isPartial: false,
    items: [
      {
        id: 'grni-002',
        productId: 'prod-005',
        productName: 'Nút nhựa 15mm',
        expectedQty: 3000,
        receivedQty: 2800,
        acceptedQty: 2800,
        rejectedQty: 0,
        unit: 'cái',
        qcStatus: 'Pending',
        batchNo: 'LOT-05128',
        storageLocation: 'B1-05',
        notes: 'Kiểm tra mẫu, có 200 cái thiếu so PO',
      },
    ],
    receivedDate: new Date(baseDate.getTime() - 1 * 24 * 60 * 60 * 1000),
    createdAt: new Date(baseDate.getTime() - 1 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(baseDate.getTime() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'grn-003',
    code: 'GRN-2026-003',
    poId: 'po-003',
    prId: 'pr-009',
    supplierId: 'sup-001',
    supplierName: 'Vải ABC Trading Co.',
    status: 'Submitted',
    isPartial: true,
    items: [
      {
        id: 'grni-003',
        productId: 'prod-002',
        productName: 'Vải Cotton Xanh Navy',
        expectedQty: 150,
        receivedQty: 100,
        acceptedQty: 100,
        rejectedQty: 0,
        unit: 'mét',
        qcStatus: 'Pass',
        batchNo: 'LOT-05130',
        storageLocation: 'A2-03',
        notes: 'Nhận 100m, còn 50m sẽ gửi tuần tới',
      },
    ],
    receivedDate: new Date(baseDate.getTime() - 2 * 24 * 60 * 60 * 1000),
    createdAt: new Date(baseDate.getTime() - 2 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(baseDate.getTime() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'grn-004',
    code: 'GRN-2026-004',
    poId: 'po-004',
    prId: 'pr-009',
    supplierId: 'sup-001',
    supplierName: 'Vải ABC Trading Co.',
    status: 'Completed',
    isPartial: false,
    items: [
      {
        id: 'grni-004',
        productId: 'prod-004',
        productName: 'Vải Lụa Kem',
        expectedQty: 120,
        receivedQty: 120,
        acceptedQty: 120,
        rejectedQty: 0,
        unit: 'mét',
        qcStatus: 'Pass',
        batchNo: 'LOT-05135',
        storageLocation: 'A3-01',
        notes: 'Đạt chuẩn, đóng gói tốt',
      },
    ],
    receivedDate: new Date(baseDate.getTime() - 6 * 24 * 60 * 60 * 1000),
    createdAt: new Date(baseDate.getTime() - 6 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(baseDate.getTime() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'grn-005',
    code: 'GRN-2026-005',
    poId: 'po-005',
    prId: 'pr-010',
    supplierId: 'sup-003',
    supplierName: 'Vải Lụa Hạnh Phúc',
    status: 'Completed',
    isPartial: false,
    items: [
      {
        id: 'grni-005',
        productId: 'prod-009',
        productName: 'Chỉ may lụa màu',
        expectedQty: 500,
        receivedQty: 500,
        acceptedQty: 500,
        rejectedQty: 0,
        unit: 'cuộn',
        qcStatus: 'Pass',
        batchNo: 'LOT-05136',
        storageLocation: 'B2-02',
        notes: 'Đủ 500 cuộn, chất lượng cao',
      },
    ],
    receivedDate: new Date(baseDate.getTime() - 4 * 24 * 60 * 60 * 1000),
    createdAt: new Date(baseDate.getTime() - 4 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(baseDate.getTime() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'grn-006',
    code: 'GRN-2026-006',
    poId: 'po-006',
    prId: 'pr-011',
    supplierId: 'sup-004',
    supplierName: 'NCC Nút Bấm 123',
    status: 'Received',
    isPartial: false,
    items: [
      {
        id: 'grni-006',
        productId: 'prod-010',
        productName: 'Túi nilon in logo',
        expectedQty: 10000,
        receivedQty: 10000,
        acceptedQty: 9500,
        rejectedQty: 500,
        unit: 'cái',
        qcStatus: 'Pending',
        batchNo: 'LOT-05137',
        storageLocation: 'C1-03',
        notes: 'Chờ kiểm chất lượng in logo',
      },
    ],
    receivedDate: new Date(baseDate.getTime() - 3 * 24 * 60 * 60 * 1000),
    createdAt: new Date(baseDate.getTime() - 3 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(baseDate.getTime() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'grn-007',
    code: 'GRN-2026-007',
    poId: 'po-007',
    prId: 'pr-012',
    supplierId: 'sup-001',
    supplierName: 'Vải ABC Trading Co.',
    status: 'Completed',
    isPartial: false,
    items: [
      {
        id: 'grni-007',
        productId: 'prod-001',
        productName: 'Vải Cotton Trắng',
        expectedQty: 300,
        receivedQty: 300,
        acceptedQty: 300,
        rejectedQty: 0,
        unit: 'mét',
        qcStatus: 'Pass',
        batchNo: 'LOT-05138',
        storageLocation: 'A2-05',
        notes: 'Chất lượng cao, khổ 150cm',
      },
    ],
    receivedDate: new Date(baseDate.getTime() - 8 * 24 * 60 * 60 * 1000),
    createdAt: new Date(baseDate.getTime() - 8 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(baseDate.getTime() - 7 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'grn-008',
    code: 'GRN-2026-008',
    poId: 'po-008',
    prId: 'pr-013',
    supplierId: 'sup-002',
    supplierName: 'Phụ Liệu XYZ',
    status: 'QC In Progress',
    isPartial: false,
    items: [
      {
        id: 'grni-008',
        productId: 'prod-005',
        productName: 'Nút nhựa 15mm',
        expectedQty: 8000,
        receivedQty: 8000,
        acceptedQty: 7800,
        rejectedQty: 200,
        unit: 'cái',
        qcStatus: 'Pending',
        batchNo: 'LOT-05139',
        storageLocation: 'B1-06',
        notes: 'Đang kiểm tra chất lượng màu sắc',
      },
    ],
    receivedDate: new Date(baseDate.getTime() - 1 * 24 * 60 * 60 * 1000),
    createdAt: new Date(baseDate.getTime() - 1 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(baseDate.getTime() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'grn-009',
    code: 'GRN-2026-009',
    poId: 'po-009',
    prId: 'pr-003',
    supplierId: 'sup-005',
    supplierName: 'Cotton Premium',
    status: 'Completed',
    isPartial: false,
    items: [
      {
        id: 'grni-009',
        productId: 'prod-002',
        productName: 'Vải Cotton Xanh Navy',
        expectedQty: 200,
        receivedQty: 200,
        acceptedQty: 200,
        rejectedQty: 0,
        unit: 'mét',
        qcStatus: 'Pass',
        batchNo: 'LOT-05140',
        storageLocation: 'A2-07',
        notes: 'Đạt chuẩn, nhuộm đều',
      },
      {
        id: 'grni-010',
        productId: 'prod-003',
        productName: 'Vải Cotton Đỏ Đô',
        expectedQty: 150,
        receivedQty: 150,
        acceptedQty: 150,
        rejectedQty: 0,
        unit: 'mét',
        qcStatus: 'Pass',
        batchNo: 'LOT-05141',
        storageLocation: 'A3-02',
        notes: 'Màu đẹp, chất lượng tốt',
      },
    ],
    receivedDate: new Date(baseDate.getTime() - 12 * 24 * 60 * 60 * 1000),
    createdAt: new Date(baseDate.getTime() - 12 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(baseDate.getTime() - 10 * 24 * 60 * 60 * 1000),
  },
]

export const mockReturns: IReturn[] = [
  {
    id: 'ret-001',
    grnId: 'grn-002',
    returnDate: new Date(baseDate.getTime() - 1 * 24 * 60 * 60 * 1000),
    reason: 'over_delivery',
    items: [
      {
        productId: 'prod-005',
        productName: 'Nút nhựa 15mm',
        returnQty: 200,
        unit: 'cái',
      },
    ],
    status: 'pending',
  },
  {
    id: 'ret-002',
    grnId: 'grn-003',
    returnDate: new Date(baseDate.getTime() - 2 * 24 * 60 * 60 * 1000),
    reason: 'wrong_item',
    items: [
      {
        productId: 'prod-002',
        productName: 'Vải Cotton Xanh Navy',
        returnQty: 10,
        unit: 'mét',
      },
    ],
    status: 'pending',
    creditNoteNo: 'CN-2026-001',
  },
  {
    id: 'ret-003',
    grnId: 'grn-006',
    returnDate: new Date(baseDate.getTime() - 2 * 24 * 60 * 60 * 1000),
    reason: 'quality_fail',
    items: [
      {
        productId: 'prod-010',
        productName: 'Túi nilon in logo',
        returnQty: 500,
        unit: 'cái',
      },
    ],
    status: 'in_transit',
  },
]
